### ISSUE TITLE
Deprecation warning with simple_form 3.1

### ISSUE THREAD

**Issue by handylearn** [elfassy/simple_dragonfly_preview#12]
If I follow the readme, image upload and preview works great, but I get a deprecation warning generated by simple_form in the log file:

> DEPRECATION WARNING: input method now accepts a `wrapper_options` argument. 
> The method definition without the argument is deprecated and will be removed in the next Simple Form version.  
> Change your code from:
> 
> ```
>  def input
> 
>  to
> 
>  def input(wrapper_options)
> ```
> 
> See https://github.com/plataformatec/simple_form/pull/997 for more information.
> ...
> Rendered ....simple_dragonfly_preview-0.0.5/app/views/simple_dragonfly_preview/image/_form.html.erb

I used the following to call simple_dragonfly_preview:
     <%= simple_form_for(@order_place) do |f| %>
         <%= f.input :image, as: :image_preview, size:'180x180#' %>

**Comment by handylearn** [comment]
It looks like matfiz has already worked on this issue. but it was not released by now:
https://github.com/elfassy/simple_dragonfly_preview/commit/60604e4c708f8575ad573de37783af61075109ea

**Comment by elfassy** [comment]
thanks! would be great if @matfiz can submit a pull request. Otherwise I'll add it in the next week when I get a min :)

**Comment by elfassy** [comment]
I'll release a new version shortly

**Comment by matfiz** [comment]
I will give it a look in the evening :)

wt., 15 mar 2016, 16:58 użytkownik Michael Elfassy <notifications@github.com>
napisał:

**Comment by elfassy** [comment]
sorry @matfiz your commit is already merged, answered too quickly. 
@handylearn i've deployed a new version https://rubygems.org/gems/simple_dragonfly_preview
cheers

**Comment by matfiz** [comment]
Ok, great!

wt., 15 mar 2016, 17:42 użytkownik Michael Elfassy <notifications@github.com>
napisał:
