### ISSUE TITLE
Preview loads, but input states "no file selected"

### ISSUE THREAD

**Issue by bodrovis** [elfassy/simple_dragonfly_preview#7]
As per this discussion https://github.com/elfassy/simple_dragonfly_preview/issues/6#issuecomment-44295899

The preview loads without any problems but the value of the file field states "No file selected" which can be quite strange for a user. See the screenshot:

![untitled](https://cloud.githubusercontent.com/assets/646942/3093962/45196bd6-e5b7-11e3-9817-f45f891c0af6.png)

**Comment by elfassy** [comment]
This is a tricky one. The text "No file selected" comes from the browser. We could just do a custom browse button. Thoughts?

**Comment by bodrovis** [comment]
Well, that's might be a nice solution. :)

**Comment by elfassy** [comment]
how about the ability to inject custom css to the button iframe. That way the button can be customized to what people want. The default css can something like this: http://jsfiddle.net/Lsgbx5ne/1/

**Comment by bodrovis** [comment]
Interesting, but this does not work with Firefox https://i.imgur.com/IZPoEtZ.png :( In Chrome everything is fine. There are lots of other techniques, however all of them are pretty cumbersome https://duckduckgo.com/?q=styling+file+input+button&ia=qa
